- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.bash:    
    ~/.bashrc:
    ~/.profile:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.shell:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:

- shell:
    # the following have to run after linking ~/.gitconfig
    - git update-submodules
    - >
      git cleanall -f
      vim/bundle/
